$scoreboard players set @s brp.base $(value)
scoreboard players operation @s brp.half = @s brp.base
scoreboard players operation @s brp.half /= 2 constant
scoreboard players operation @s brp.fifth = @s brp.base
scoreboard players operation @s brp.fifth /= 5 constant
tellraw @a {"translate": "[%s]正在暗骰","with": [{"selector":"@s"}]}
$execute if score @s trpg.result matches 50.. if score @s trpg.result matches 100.. run tellraw @s {"translate": "[%s]%s/%s%s大失败!","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}
$execute unless score @s trpg.result matches 50.. if score @s trpg.result matches 96.. run tellraw @s {"translate": "[%s]%s/%s%s大失败!","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}
$execute if score @s trpg.result matches 50.. unless score @s trpg.result matches 100.. if score @s trpg.result > @s brp.base run tellraw @s {"translate": "[%s]%s/%s%s失败","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}
$execute unless score @s trpg.result matches 50.. unless score @s trpg.result matches 96.. if score @s trpg.result > @s brp.base run tellraw @s {"translate": "[%s]%s/%s%s失败","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}
$execute unless score @s trpg.result > @s brp.base if score @s trpg.result > @s brp.half run tellraw @s {"translate": "[%s]%s/%s%s常规成功","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}
$execute unless score @s trpg.result > @s brp.half if score @s trpg.result > @s brp.fifth run tellraw @s {"translate": "[%s]%s/%s%s困难成功","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}
$execute unless score @s trpg.result > @s brp.fifth unless score @s trpg.result matches ..1 run tellraw @s {"translate": "[%s]%s/%s%s极难成功","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}
$execute if score @s trpg.result matches ..1 run tellraw @s {"translate": "[%s]%s/%s%s大成功!","with": [{"selector":"@s"},{"score": {"name": "@s","objective": "trpg.result"},"color":"yellow"},{"score": {"name": "@s","objective": "brp.base"}},{"text": "$(skill)","color": "light_purple","clickEvent": {"action": "run_command","value": "/function roll:return {input:'$(input)',name:'$(name)',enchantment:$(enchantment),lvl:$(lvl),}"}}]}